import { SidebarsConfig } from '@docusaurus/plugin-content-docs'

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: 'autogenerated', dirName: 'tutorial' }],

  documentationSidebar: [
    {
      type: 'doc',
      label: 'Read Me',
      id: 'api/README'
    },
    {
      type: 'doc',
      label: 'YouTube Class (use this)',
      id: 'api/Library-Exports/classes/YouTube'
    },
    {
      type: 'category',
      label: 'Classes',
      items: [
        { type: 'autogenerated', dirName: 'api/Library-Exports/classes' }
      ]
    },
    {
      type: 'category',
      label: 'Authenticated Classes',
      items: [
        { type: 'autogenerated', dirName: 'api/OAuth/classes' }
      ]
    },
    {
      type: 'category',
      label: 'Types',
      items: [
        { type: 'autogenerated', dirName: 'api/Library-Exports/type-aliases' }
      ]
    },
    {
      type: 'doc',
      label: 'Modules',
      id: 'api/modules'
    }
  ]
}

module.exports = sidebars
