import { SidebarsConfig } from '@docusaurus/plugin-content-docs'

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: 'autogenerated', dirName: 'tutorial' }],

  documentationSidebar: [
    {
      type: 'ref',
      id: 'api/classes/Library_Exports.YouTube'
    },
    { type: 'autogenerated', dirName: 'api' }
  ]

  // But you can create a sidebar manually
  /*
    tutorialSidebar: [
      'intro',
      {
        type: 'category',
        label: 'Tutorial',
        items: ['tutorial-basics/create-a-document'],
      },
    ],
     */
}

module.exports = sidebars
