plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

pnpIgnorePatterns:
  - ./docusaurus/.*
  - ./docusaurus/**

yarnPath: .yarn/releases/yarn-3.6.0.cjs
