approvedGitRepositories:
  - "**"

compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: false

enableScripts: true

npmAuthToken: "${NPM_TOKEN-fallback}"

npmMinimalAgeGate: 24h

npmRegistryServer: "https://registry.npmjs.org"

packageExtensions:
  docusaurus-plugin-typedoc@*:
    dependencies:
      typedoc: "*"
  mocha@*:
    dependencies:
      source-map-support: "*"
      ts-node: "*"
  typedoc@*:
    dependencies:
      typedoc-plugin-markdown: "*"

plugins:
  - checksum: a415aa1836b0b2408064cbcd6c629ce1440836f46a62d54e715b21fa7f9c6fabcc1d8affeba4593c06ee313eda335006c782d09f574352ec4de4c493b47b1c94
    path: .yarn/plugins/check-node-version.cjs
    spec: "https://raw.githubusercontent.com/Akryum/yarn-check-node/76292874d34510ca1b3b8350f5f2861f50b97efb/bundle/check-node-version.js"

tsEnableAutoTypes: false

yarnPath: .yarn/releases/yarn-4.16.0.cjs
