compressionLevel: mixed

enableGlobalCache: false

npmAuthToken: "${NPM_TOKEN-fallback}"

npmRegistryServer: "https://registry.npmjs.org"

yarnPath: .yarn/releases/yarn-4.10.3.cjs

packageExtensions:
  "docusaurus-plugin-typedoc@*":
    dependencies:
      typedoc: "*"
  "typedoc@*":
    dependencies:
      typedoc-plugin-markdown: "*"
  "mocha@*":
    dependencies:
      "source-map-support": "*"
      "ts-node": "*"
