name: Development

on:
  push:
    branches:
      - 'master'
    paths:
        - 'src/**'
        - 'scripts/**'
        - 'tests/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    name: Lint and type check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version: '23.x'
    - name: Lint
      uses: borales/actions-yarn@v5
      with:
        cmd: lint
    - name: Build typings (type check)
      uses: borales/actions-yarn@v5
      with:
        cmd: build
    - name: Test build of documentatation
      uses: borales/actions-yarn@v5
      with:
        cmd: docs:build
      env:
        DOCSEARCH_APP_ID: ${{ secrets.DOCSEARCH_APP_ID }}
        DOCSEARCH_API_KEY: ${{ secrets.DOCSEARCH_API_KEY }}
        DOCSEARCH_ASSISTANT_ID: ${{ secrets.DOCSEARCH_ASSISTANT_ID }}
  test:
    name: Test and upload coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version: '23.x'
    - name: Test and generate coverage
      uses: borales/actions-yarn@v5
      with:
        cmd: coverage
      env:
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v6
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage/coverage-final.json
    - name: Upload test results to Codecov
      if: ${{ !cancelled() }}
      uses: codecov/codecov-action@v6
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage/tests-dev.junit.xml
        report_type: test_results
