name: Publish

on:
  release:
    types: [released]
  workflow_dispatch:

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  publish-docs:
    name: Publish documenation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
      with:
        ref: 'release'
    - name: Set git user
      run: |
          git config --global user.name "Brandon Bothell"
          git config --global user.email "brandon@brandonsbench.net"
    - uses: actions/setup-node@v7
      with:
        node-version: '23.x'
    - name: Install dependencies
      run: |
        corepack enable
        yarn
    - name: Publish Docs
      run: |
        yarn docs:publish
      env:
        GIT_USER: brandonbothell
        GIT_PASS: ${{ secrets.GIT_ACCESS_TOKEN }}
        CURRENT_BRANCH: master
        DOCSEARCH_APP_ID: ${{ secrets.DOCSEARCH_APP_ID }}
        DOCSEARCH_API_KEY: ${{ secrets.DOCSEARCH_API_KEY }}
        DOCSEARCH_ASSISTANT_ID: ${{ secrets.DOCSEARCH_ASSISTANT_ID }}
  publish-npm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-node@v7
      with:
        node-version: '23.x'
    - name: Install dependencies
      run: |
        corepack enable
        yarn
    - name: Build and Publish Package
      run: |
        yarn run publish
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
