name: Renovate

on:
  push:
    branches:
      - 'renovate/**'
    paths:
      - 'package.json'
      - '.github/**/*.yml'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Checkout and Set Git User
      run: |
          git config --global user.name "Brandon Bothell"
          git config --global user.email "bothellbrandon@gmail.com"
    - uses: actions/setup-node@v3.6.0
      with:
        node-version: '20.3.0'
    - name: Clean yarn cache
      uses: borales/actions-yarn@v4
      with:
        cmd: cache clean
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Install dependencies and update lockfile
      uses: borales/actions-yarn@v4
      with:
        cmd: install # will run `yarn install` command
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Lint
      uses: borales/actions-yarn@v4
      with:
        cmd: lint
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Build
      uses: borales/actions-yarn@v4
      with:
        cmd: build
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Build Docs
      uses: borales/actions-yarn@v4
      with:
        cmd: docs:build
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Test and generate coverage
      uses: borales/actions-yarn@v4
      with:
        cmd: coverage
      env:
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage/coverage-final.json
    # - name: Commit dependency files
    #   run: |
    #     git add .yarn/ .pnp.* yarn.lock docusaurus/.yarn/ docusaurus/.pnp.* docusaurus/yarn.lock
    #     git commit -m "chore(deps): update lockfile and package cache"
    # - name: Push dependency files
    #   uses: ad-m/github-push-action@v0.6.0
    #   with:
    #     github_token: ${{ secrets.GIT_ACCESS_TOKEN }}
    #     branch: ${{ github.ref }}
