name: Renovate

on:
  pull_request:
  workflow_dispatch:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # - name: Checkout and Set Git User
    #   run: |
    #       git config --global user.name "Brandon Bothell"
    #       git config --global user.email "bothellbrandon@gmail.com"
    - uses: actions/setup-node@v3.8.2
      with:
        node-version: '20.5.0'
    - name: Lint
      uses: borales/actions-yarn@v4
      with:
        cmd: lint
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Build
      uses: borales/actions-yarn@v4
      with:
        cmd: build
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Test build of documentation
      uses: borales/actions-yarn@v4
      with:
        cmd: docs:build
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Run unit tests
      uses: borales/actions-yarn@v4
      with:
        cmd: test
      env:
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    # - name: Commit dependency files
    #   run: |
    #     git add .yarn/ .pnp.* yarn.lock docusaurus/.yarn/ docusaurus/.pnp.* docusaurus/yarn.lock
    #     git commit -m "chore(deps): update lockfile and package cache"
    # - name: Push dependency files
    #   uses: ad-m/github-push-action@v0.6.0
    #   with:
    #     github_token: ${{ secrets.GIT_ACCESS_TOKEN }}
    #     branch: ${{ github.ref }}
