name: Renovate

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-node@v6
      with:
        node-version: '23.x'
    - name: Install dependencies
      run: |
        corepack enable
        yarn
    - name: Lint
      run: |
        yarn lint
    - name: Build
      run: |
        yarn build
    - name: Test build of documentation
      run: |
        yarn docs:build
      env:
        DOCSEARCH_APP_ID: ${{ secrets.DOCSEARCH_APP_ID }}
        DOCSEARCH_API_KEY: ${{ secrets.DOCSEARCH_API_KEY }}
        DOCSEARCH_ASSISTANT_ID: ${{ secrets.DOCSEARCH_ASSISTANT_ID }}
    - name: Unit tests
      run: |
        yarn test
      env:
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
